[book]
title = "Abitus Contracts"
language = "en"
multilingual = false

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/AbitusLabs/contracts"
